### ISSUE TITLE
安装cloud-init 之后虚拟机ssh 无法连接

### ISSUE THREAD

**Issue by sfPPP** [sfPPP/openstack-note#82]
在安装cloud-init 之前改过sshd_config配置之后虚拟机ssh可以正常连接
安装cloud-init之后虚拟机正常启动但是ssh无法连接到虚拟机，查看ssh服务正常
查看ssh配置文件，发现配置文件被更改

  **PasswordAuthentication yes** 被改成了  **PasswordAuthentication no**
然后查看cloud的配置文件
**/etc/cloud/cloud.cfg** 
发现了关于ssh的配置
```
        # vim /etc/cloud/cloud.cfg

       users:
        - default
  
       disable_root: 1
       ssh_pwauth:  0
```
cloud-init 配置默认禁止ssh密码登陆，而且禁止root用户登陆
更改配置项为
 **disable_root: 0
 ssh_pwauth:  1**
重启关机打快照启动虚拟机之后ssh连接恢复正常
